### ISSUE TITLE
关于appsettings.json路径

### ISSUE THREAD

**Issue by l6061379** [hetaoos/Cloud189Checkin#2]
我是设备是QNAP，用docker搜索到直接安装Cloud189Checkin，那appsettings.json这个路径在哪里，我是不是要找到这个文件，然后修改里面的账号？

**Comment by hetaoos** [comment]
不用找，直接自己创建一个。
然后绑定到：
/app/appsettings.json

**Comment by Liuruicheng520** [comment]
请问 这个能抽奖嘛？签到后 应该还有两次抽奖~~~

**Comment by hetaoos** [comment]
> 请问 这个能抽奖嘛？签到后 应该还有两次抽奖~~~

抽奖的。
